### ISSUE TITLE
Need CI/CD system for vignettes

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-consumer-vignettes#28] opened 2019-04-25 13:35 UTC
As a user of vignettes I expect that the code will always work, and not become obsolete. 

The main vignettes on the home page should have a CI/CD system implemented to assure that they are retested regularly.

**Comment by natanlao** [comment] 2019-07-31 17:44
Dupe of #31

**Closed by natanlao** 2019-07-31 17:44 UTC
Labels: Epic
